#!/usr/bin/php
<?php

$root = getcwd();
elation_readpaths($root);

require_once("include/app_class.php");

if (count($argv) >= 2) {
  $script = array_shift($argv);
  $component = array_shift($argv);
  $componentargs = array();
  if (!empty($argv)) {
    foreach ($argv as $arg) {
      list($k, $v) = explode("=", $arg, 2);
      $componentargs[$k] = $v;
    }
  }
  $app = new App($root, $componentargs);
  print $app->display("/" . str_replace(".", "/", $component), $componentargs);
}

function elation_addroot($roots) {
  $path = explode(PATH_SEPARATOR, get_include_path());
  if (!is_array($roots)) {
    $roots = array($roots);
  }
  
  if ($path[0] == ".") // . should always be first
    array_shift($path);
  $path = array_merge($roots, $path);
  array_unshift($path, ".");

  set_include_path(implode(PATH_SEPARATOR, $path));
}
function elation_readpaths($root) {
  $matches = array(); 
  $homedir = $_ENV['HOME'] . '/';
  
  $paths = file_get_contents('config/elation.path');
  
  if($paths !== false) {
    $paths = explode(PHP_EOL, $paths);
    $newpaths = array($root);
    foreach($paths as $path) {
      if(!empty($path)) {
        if($homedir) {
          $path = str_replace('~/', $homedir, $path);
        }
        $newpaths[] = $path;
      }
    }
    elation_addroot($newpaths);
  }
}
